### ISSUE TITLE
Try zipping exiftool and perl directly in lambda package

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ingest#1]
see: https://github.com/pplu/perl-aws-lambda/issues/1#issuecomment-351518539

**Comment by postfalk** [comment]
Yes, the challenge lies to move the executable and all the required header files from /usr/bin or wherever it ends up to a path that is part of the deployment packages and set the path in the lambda function such that it becomes executable. Sometimes this is really complicated and requires a re-compile. Sometimes it is as easy as moving the file. Given the fact that you are able to run this from the /tmp folder you should be able to run it from you deploy package as well. (or is there a permission issue involved you are trying to solve?)

**Comment by postfalk** [comment]
One more thing on this. It is OK to use some prefix/folder to indicate where images in that bucket go but from there down I would treat any "/" just as part of the prefix. So users would be able to upload/create directories but it would not matter for the pipeline (this path would become part of the original filename and duplicate uploads would just be dealt with via hash).
