### ISSUE TITLE
Handle duplicate uploads

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ingest#10]
If the image is already in s3, s3 will just overwrite the image and this triggers the s3 ObjectCreate event, the lambda still gets fired and a post request is made to the backend. Figure out a filter for this so that lambda fires but doesn't send post.

**Comment by postfalk** [comment]
Might be actually simpler to enforce a unique constraint on the data and reject that POST when it arrives. Error catching instead of creating complicated logics to avoid them

**Comment by nathanielrindlaub** [comment]
Update: I modified the behavior following @postfalk's recommendation, so duplicate images will get rejected by ```CreateImage``` requests to the animl-api (there's a unique constrain on both the image's hash, which is used for its ```_id``` field, and an [unique compound index](https://docs.mongodb.com/manual/core/index-unique/#unique-compound-index) set on the the ```DateTimeCreated``` + ```SerialNumber``` fields). When the API responds with an error indicating there was a duplicate, animl-ingest moves the image to a dead-letter-bucket and files it under a ```/duplicates/``` "directory".
