### ISSUE TITLE
Exif function stored in S3?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-ingest#11]
Hi Natty, I just reading the README.md, the part where you mention that you store the exiftool library in S3 to save space. Is there an advantage to keeping the Lambda package small. I would just compile everything into the package. I have done that with much bigger dependencies. 

Your approach seems to be somewhat convoluted. There is no need to keep Lambda functions small you can run entire Django web applications in Lambda. 

Falk

**Comment by nathanielrindlaub** [comment]
On my todos. See #1
