### ISSUE TITLE
Normalize file extensions (make lowercase)

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ingest#22]
images with uppercase file extensions, which reconyx images have (e.g. IMG_0026.JPG), cause issues with cloudfront when trying to access the production version (d3ps2k4314vkoe.cloudfront.net/small/9c376a840a07a5c3f5a700878d02382e-small.JPG)

**Comment by postfalk** [comment]
Oh these Windows people. Capitalization does not matter on Windows machine but users love to through random capitalization around.

**Comment by nathanielrindlaub** [comment]
Done
