### ISSUE TITLE
Upgrade to Python 3.9

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ingest#28]
See same issue here: https://github.com/tnc-ca-geo/animl-email-relay/issues/5

**Comment by postfalk** [comment]
Shouldn't we go for 3.11 once Lambda provides it? Good upgrade to be backed by a test suite.

**Comment by postfalk** [comment]
nose (test runner) does not play along with Python 3.10+ (yet?). Maybe using nose is superseded by some new onboard tools, Check!

**Comment by nathanielrindlaub** [comment]
No longer relevant since we broke the Python piece into it's own service (https://github.com/tnc-ca-geo/exif-api)
