### ISSUE TITLE
Create email to S3 pipeline

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-ingest#3]
Most networked camera traps support sending images via email (and I think the Buckeye does too). It is certainly true for cellular cameras. So we do need a scheduled lambda function that checks email and copies attachments over. 

There are different techniques. Most programming languages have pop3 or smtp clients. However, newer email platforms, e.g. Gmail want you to use there REST backend to retrieve messages.

**Comment by nathanielrindlaub** [comment]
I started to build this out [here](https://github.com/tnc-ca-geo/animl-email-relay), but got stalled out b/c the UOvision WiFi camera traps we bought do not include camera serial number (or the full size image) in their email alerts. UOvision and Reconyx also discontinued their WiFi cameras, so we're in the market for new ones. Closing this out for now.
