### ISSUE TITLE
Is there a particular reason why we are using the ntpath module on S3 keys?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-ingest#40]
Does it has to do with the fact that the images coming from a Windows server? If so I would normalize the keys in the upload process. Otherwise I would check whether boto3 or botocore provides similar functionality or maybe it is simple enough to just to a path.split('/')[-1]

**Comment by nathanielrindlaub** [comment]
Happy to look into this @postfalk - do you mind including a link to the exact line in the code you're referring to?
