### ISSUE TITLE
[Question] how retries work in the context of FIFO queues

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ingest#50]
Hey @ingalls, 

After encountering a [Sagemaker issue](https://github.com/tnc-ca-geo/animl-api/issues/94) with a batch of 50 images, I took a look at the logs and the timestamps for the inference worker invocations and got a little worried that problematic images & failed inference attempts could end up really gumming up the FIFO queues and causing long delays.

The logs seem to suggest that the FIFO queue's redrive policy its set to retry messages 3 times w/ 20 mins between each try before moving to dlq? 20 mins seems like a lot no? is there a way to make that shorter?

**Comment by ingalls** [comment]
@nathanielrindlaub Per our convo yesterday:
- @nathanielrindlaub was going to ask AWS about retry logic as we couldn't find anything in the logs & cloudformation that allowed us to manually configure time between retries other than total number of retries & the visibility timeout. 
- We can increase the Batch Size to 10 if we want to increase concurrency and therefore reduce total image throughput even if we have to live with longer retries. We can also add a SageMaker instance specific to Batch and then remove the priority checks as this should reduce retries to only be needed for errors.

**Comment by nathanielrindlaub** [comment]
@ingalls - I asked AWS and they've opened as separate ticket w/ the SQS support team about this question. I'll keep you posted.

**Comment by nathanielrindlaub** [comment]
Ok @ingalls so heard back from AWS support, and the issue was our [`VisibilityTimeout`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-visibilitytimeout) setting, for which the units are seconds & we have it set to 1200 (=20 mins). So that explains it. 

My understanding is that we should set the visibility timeout to a little over the max expected time for processing an image and removing it from the queue. So maybe like 7 seconds? When things go well the wall time is around 4.5 seconds but I'm not sure if there are errors (the inference lambda's `timeout` is currently set to 120 seconds). Do you recommend setting it to 120?

**Comment by ingalls** [comment]
@nathanielrindlaub Yeah 120 sounds like a good start - let me know how that looks in the logs.
