### ISSUE TITLE
[Question] Batch resources w/o <stage> appended to their names?

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ingest#51]
Some of the batch resources defined in animl-ingest serverless config (e.g. BatchJobDefinititon) don't appear to append the stage to their names. Just want to be sure sure this will be OK when deploying to prod?

**Comment by ingalls** [comment]
@nathanielrindlaub Anything that contains the `AWS::StackName` variable should be unique to the stage as the Stage is included in the StackName. 

Output from `aws cloudformation list-stacks`
```
            "StackName": "animl-ingest-dev"
            "StackName": "animl-ingest-prod"
```

As such it shouldn't hamper our deploy to production :)
