### ISSUE TITLE
When puting unzipped images in S3, include original file path & name in Key

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ingest#53]
From convo on Auto Queue PR: https://github.com/tnc-ca-geo/animl-ingest/pull/45#discussion_r1172087878

**Comment by nathanielrindlaub** [comment]
Important for errors CSV too. See #42

**Comment by ingalls** [comment]
The new Zip library that we use now includes the full path in the entry object. I've simply replaced the `/` directory with a `-` so the full name is retained. The hashed methodology is now removed.

Via: https://github.com/tnc-ca-geo/animl-ingest/pull/57
